spring.datasource.url=jdbc:h2:mem:lycee-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.port=8080
spring.application.name=LyceeApp
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.main.allow-bean-definition-overriding=true
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
spring.jackson.time-zone=UTC
spring.mail.host=smtp.example.com
spring.mail.port=587
